# Custom means that it will use the Dockerfile
runtime: custom 

# Flex environment required for WebSocket support, which is required for PeerJS.
env: flex 

# Limit resources to one instance, one CPU, very little memory or disk.
instance_class: F1
