name: deploy-server
on:
  workflow_run:
    workflows: ["lint-test-build"]
    branches: [production]
    types: [completed]

env:
  server_url: https://deai-313515.ew.r.appspot.com/

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: production
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: |
            discojs/package-lock.json
            server/package-lock.json

      - run: npm ci
        working-directory: discojs
      - run: npm run build
        working-directory: discojs/discojs-node

      - name: authenticate-to-google-cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: deploy-to-google-cloud
        uses: google-github-actions/deploy-appengine@v0.8.0
        with:
          working_directory: .
          deliverables: app.yaml
          version: prod
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: test
        run: curl "${{ env.server_url }}"
