name: github-pages
on:
  workflow_run:
    workflows: ["lint-test-build"]
    branches: [production]
    types: [completed]

jobs:
  gh-pages-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: |
            discojs/package-lock.json
            web-client/package-lock.json

      - run: npm ci
        working-directory: discojs
      - run: npm run build
        working-directory: discojs/discojs-web
      - run: npm ci && npm run build
        working-directory: web-client
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./web-client/dist"

  gh-pages-deploy:
    needs: gh-pages-build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
